### ISSUE TITLE
Enhanced Battletest.dll missing

### ISSUE THREAD

**Issue by hannibalbarcid** [cookgreen/EnhancedBattleTest#2]
![Screenshot (809)](https://user-images.githubusercontent.com/121701758/210121787-cb1b1c89-b395-477a-89f5-7217519f5630.png)

**Comment by hannibalbarcid** [comment]
Note this i with the source code here https://github.com/cookgreen/EnhancedBattleTest/

The Main file here is good. https://github.com/cookgreen/EnhancedBattleTest/releases

**Comment by cookgreen** [comment]
yeah, please use release
