### ISSUE TITLE
Enhanced Battle Test for 1.2.8!!

### ISSUE THREAD

**Issue by Revan401** [cookgreen/EnhancedBattleTest#4]
If, in your free time you are able to update Enhanced Battle Test mod to v1.2.8 I would be eternally in your debt, thank you brother.

**Comment by cookgreen** [comment]
ok

**Comment by MrChickenBannerlord** [comment]
Hi, I made an account just to say thank you for updating the mod in the first place. I have a small YT channel where I make Bannerlord videos. A lot of my videos are about testing units, and this mod is perfect for this. I really hope you might have the free time to be able to update this to the new version :)

**Comment by cookgreen** [comment]
> Hi, I made an account just to say thank you for updating the mod in the first place. I have a small YT channel where I make Bannerlord videos. A lot of my videos are about testing units, and this mod is perfect for this. I really hope you might have the free time to be able to update this to the new version :)

I am processing the update
